#####################################
#   Configured for: Magento 2.4.4 + Varnish
#####################################
version: '3.8'
services:
  redis-cache:
    image: redis:6.2
    volumes:
      - redis/6379-redis-cache.conf:/usr/local/etc/redis/redis.conf
    command: [redis-server,/usr/local/etc/redis/redis.conf]
    ports:
      - "6379:6379"
  redis-fpc:
    image: redis:6.2
    volumes:
      - redis/6380-redis-cache.conf:/usr/local/etc/redis/redis.conf
    command: [redis-server,/usr/local/etc/redis/redis.conf]
    ports:
      - "6380:6380"
  redis-session:
    image: redis:6.2
    volumes:
      - redis/6381-redis-cache.conf:/usr/local/etc/redis/redis.conf
    command: [redis-server,/usr/local/etc/redis/redis.conf]
    ports:
      - "6381:6381"
  db:
    image: mysql:8
    volumes:
      - mysqldb:/var/lib/mysql
      - mysql/magento.my.cnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento
  elasticsearch:
    image: elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.16.3
    ports:
      - "5601:5601"
  mail:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8025:8025" # web ui
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis-cache:redis-cache:6379,redis-fpc:redis-fpc:6380,redis-session:redis-session:6381
    ports:
      - "8081:8081" #web UI
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
volumes:
  mysqldb:
  esdata1: