#####################################
#   Configured for: Magento 2.3 + Varnish
#####################################
version: '3.7'
services:
  web:
    image: wwright/magento2-web-local
    volumes:
     - F:/www/docker-magento2/dev/magento/app/code:/var/www/html/current/app/code:ro
     - F:/www/docker-magento2/dev/magento/app/design:/var/www/html/current/app/design:ro
     - F:/www/docker-magento2/dev/magento/app/etc:/var/www/html/current/app/etc:delegated
     - F:/www/docker-magento2/dev/magento/pub/.htaccess:/var/www/html/current/pub/.htaccess:ro
     - F:/www/docker-magento2/dev/magento/pub/static/.htaccess:/var/www/html/current/pub/static/.htaccess:delegated
     - F:/www/docker-magento2/dev/magento/pub/media:/var/www/html/current/pub/media:delegated
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1
      - PHP_IDE_CONFIG=serverName=local.magento2.com
    depends_on:
     - redis-cache
     - redis-fpc
     - redis-session
     - db
  redis-cache:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6379-redis-cache.conf]
  redis-fpc:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6380-redis-fpc.conf]
  redis-session:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6381-redis-sessions.conf]
  db:
    image: wwright/magento2-db:2.4
    volumes:
     - mysqldb:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password123
     - MYSQL_DATABASE=magento
  varnish:
    image: wwright/magento2-varnish:2.4
    depends_on:
     - web
  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
     - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: kibana:6.8.3
    ports:
     - 5601:5601
  haproxy:
    image: wwright/magento2-haproxy
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - varnish
volumes:
  mysqldb:
  esdata1: