#####################################
#   Configured for: Magento 2.4.1
#####################################
version: '3.8'
services:
  web:
    image: wwright/magento2-web-local:2.4.1
    volumes:
      - ./magento:/var/www/html/current
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1
      - PHP_IDE_CONFIG=serverName=local.magento2.com
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
      - db
  haproxy:
    image: haproxy:2.6-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/haproxy.pem:/etc/ssl/private/haproxy.pem:ro
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - web
  redis-cache:
    image: redis:5.0-alpine
    volumes:
      - ./redis/6379-redis-cache.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf]
  redis-fpc:
    image: redis:5.0-alpine
    volumes:
      - ./redis/6380-redis-fpc.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf]
  redis-session:
    image: redis:5.0-alpine
    volumes:
      - ./redis/6381-redis-sessions.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf]
  db:
    image: mysql:8
    volumes:
      - mysqldb:/var/lib/mysql
      - ./mysql/magento.my.cnf:/etc/mysql/conf.d/magento.my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento
    ports:
      - "127.0.0.1:3306:3306"
  elasticsearch:
    image: elasticsearch:7.7.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.7.1
    ports:
      - "127.0.0.1:5601:5601" # web ui
    depends_on:
      - elasticsearch
  mail:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "127.0.0.1:8025:8025" # web ui
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis-cache:redis-cache:6379,redis-fpc:redis-fpc:6380,redis-session:redis-session:6381
    ports:
      - "127.0.0.1:8081:8081" #web UI
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
volumes:
  mysqldb:
  esdata1: