#####################################
#   Configured for: Magento 2.4.7 + Varnish
#####################################
services:
  web:
    image: wwright/magento2-web-local:2.4.7
    volumes:
      - ./magento:/var/www/html/current
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1
      - PHP_IDE_CONFIG=serverName=local.magento2.com
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
      - db
  varnish:
    image: varnish:7-alpine
    volumes:
      - ./varnish/magento.vcl:/etc/varnish/magento.vcl
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    command:
      [
        "varnishd",
        "-F",
        "-f",
        "/etc/varnish/magento.vcl",
        "-s",
        "malloc,2048M",
        "-p",
        "http_resp_hdr_len=90000",
        "-p",
        "thread_pool_min=5",
        "-p",
        "thread_pool_timeout=600",
        "-p",
        "http_max_hdr=200",
        "-p",
        "http_resp_size=9000k",
        "-p",
        "workspace_backend=9000k",
      ]
    depends_on:
      - web
  haproxy:
    image: haproxy:3.1-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/haproxy.pem:/etc/ssl/private/haproxy.pem:ro
    ports:
      - "127.0.0.1:443:443"
    depends_on:
      - web
      - varnish
  redis-cache:
    image: redis:7.2-alpine
    volumes:
      - ./redis/6379-redis-cache.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-cache:/data
    command:
      [
        redis-server,
        /usr/local/etc/redis/redis.conf,
        "--save",
        "",
        "--appendonly",
        "no",
      ]
  redis-fpc:
    image: redis:7.2-alpine
    volumes:
      - ./redis/6380-redis-fpc.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-fpc:/data
    command:
      [
        redis-server,
        /usr/local/etc/redis/redis.conf,
        "--save",
        "",
        "--appendonly",
        "no",
      ]
  redis-session:
    image: redis:7.2-alpine
    volumes:
      - ./redis/6381-redis-sessions.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-session:/data
    command:
      [
        redis-server,
        /usr/local/etc/redis/redis.conf,
        "--save",
        "",
        "--appendonly",
        "no",
      ]
  db:
    image: mariadb:10.6
    volumes:
      - mariadb:/var/lib/mysql
      # - ./mariadb/maria.cnf:/etc/mysql/maria.cnf:ro
      - ./mariadb/magento.my.cnf:/etc/mysql/conf.d/magento.my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento
    ports:
      - "127.0.0.1:3306:3306"
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=.sCQb9*iH_iLyMQEqZiy
    volumes:
      - osdata:/var/lib/opensearch
    ports:
      - "127.0.0.1:9200:9200"
  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - "127.0.0.1:5601:5601" # web ui
    depends_on:
      - opensearch
  mail:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - "127.0.0.1:8025:8025" # web ui
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis-cache:redis-cache:6379,redis-fpc:redis-fpc:6380,redis-session:redis-session:6381
    ports:
      - "127.0.0.1:8081:8081" #web UI
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
volumes:
  mariadb:
  osdata:
  redis-session:
  redis-cache:
  redis-fpc:
