#####################################
#   Configured for: Magento 2.4.2
#####################################
version: '3.8'
services:
  haproxy:
    image: haproxy:2.6-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/haproxy.pem:/etc/ssl/private/haproxy.pem:ro
    ports:
      - "127.0.0.1:443:443"
  redis-cache:
    image: redis:6.0-alpine
    volumes:
      - ./redis/6379-redis-cache.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf, '--save', '', '--appendonly', 'no']
    ports:
      - "127.0.0.1:6379:6379"
  redis-fpc:
    image: redis:6.0-alpine
    volumes:
      - ./redis/6380-redis-fpc.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf, '--save', '', '--appendonly', 'no']
    ports:
      - "127.0.0.1:6380:6380"
  redis-session:
    image: redis:6.0-alpine
    volumes:
      - ./redis/6381-redis-sessions.conf:/usr/local/etc/redis/redis.conf:ro
    command: [redis-server,/usr/local/etc/redis/redis.conf, '--save', '', '--appendonly', 'no']
    ports:
      - "127.0.0.1:6381:6381"
  db:
    image: mariadb:10.4
    volumes:
      - mariadb:/var/lib/mysql
      # - ./mariadb/maria.cnf:/etc/mysql/maria.cnf:ro      
      - ./mariadb/magento.my.cnf:/etc/mysql/conf.d/magento.my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento
    ports:
      - "127.0.0.1:3306:3306"
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  kibana:
    image: kibana:7.9.3
    ports:
      - "127.0.0.1:5601:5601" # web ui
    depends_on:
      - elasticsearch
  mail:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "127.0.0.1:1025:1025" # smtphost ui
      - "127.0.0.1:8025:8025" # web ui
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis-cache:redis-cache:6379,redis-fpc:redis-fpc:6380,redis-session:redis-session:6381
    ports:
      - "127.0.0.1:8081:8081" #web UI
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
volumes:
  mariadb:
  esdata: