#####################################
#   Configured for: Magento 2.4 + Varnish
#####################################
version: '3.7'
services:
  redis-cache:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6379-redis-cache.conf]
    ports:
      - "6379:6379"
  redis-fpc:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6380-redis-fpc.conf]
    ports:
      - "6380:6380"
  redis-session:
    image: wwright/magento2-redis:2.4
    command: [redis-server,/etc/redis/6381-redis-sessions.conf]
    ports:
      - "6381:6381"
  db:
    image: wwright/magento2-db:2.4
    volumes:
     - mysqldb:/var/lib/mysql:delegated
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password123
     - MYSQL_DATABASE=magento
  varnish:
    image: wwright/magento2-varnish:2.4
    entrypoint: ["/usr/sbin/varnishd","-F","-f","/etc/varnish/varnish-external-web.vcl","-s","malloc,2048M","-p","http_resp_hdr_len=90000","-p","thread_pool_min=5","-p","thread_pool_timeout=600","-p","http_max_hdr=200","-p","http_resp_size=9000k","-p","workspace_backend=9000k"]
  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
     - esdata1:/usr/share/elasticsearch/data:delegated
    ports:
      - "9200:9200"
  kibana:
    image: kibana:6.8.3
    ports:
     - 5601:5601
  haproxy:
    image: wwright/magento2-haproxy
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - varnish
  mail:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 8025:8025 # web ui
volumes:
  mysqldb:
  esdata1: