#####################################
#   Configured for: Magento 2.4.8 + Varnish
#####################################
services:
  web:
    image: wwright/magento2-web-local:2.4.7
    volumes:
      - ./magento:/var/www/html/current
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1
      - PHP_IDE_CONFIG=serverName=local.magento2.com
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
      - db
  varnish:
    image: varnish:7-alpine
    volumes:
      - ./varnish/magento.vcl:/etc/varnish/magento.vcl
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    command:
      [
        "varnishd",
        "-F",
        "-f",
        "/etc/varnish/magento.vcl",
        "-s",
        "malloc,2048M",
        "-p",
        "http_resp_hdr_len=90000",
        "-p",
        "thread_pool_min=5",
        "-p",
        "thread_pool_timeout=600",
        "-p",
        "http_max_hdr=200",
        "-p",
        "http_resp_size=9000k",
        "-p",
        "workspace_backend=9000k",
      ]
    depends_on:
      - web
  haproxy:
    image: haproxy:3.1-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/haproxy.pem:/etc/ssl/private/haproxy.pem:ro
    ports:
      - "127.0.0.1:443:443"
    depends_on:
      - web
      - varnish
  redis-cache:
    image: valkey/valkey:8.1-alpine
    volumes:
      - redis-cache:/data
    command:
      [
        valkey-server,
        "--save",
        "",
        "--appendonly",
        "no",
        "--port",
        "6379"
      ]
  redis-fpc:
    image: valkey/valkey:8.1-alpine
    volumes:
      - redis-fpc:/data
    command:
      [
        valkey-server,
        "--save",
        "",
        "--appendonly",
        "no",
        "--port",
        "6380"
      ]
  redis-session:
    image: valkey/valkey:8.1-alpine
    volumes:
      - redis-session:/data
    command:
      [
        valkey-server,
        "--save",
        "",
        "--appendonly",
        "no",
        "--port",
        "6381"
      ]
  db:
    image: mariadb:11.4
    volumes:
      - mariadb:/var/lib/mysql
      # - ./mariadb/maria.cnf:/etc/mysql/maria.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento
    ports:
      - "127.0.0.1:3306:3306"
  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=0penSearch!23
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - osdata:/var/lib/opensearch
  dashboards:
    image: wwright/opensearch-dashboards-no-security:3
    ports:
      - "127.0.0.1:5601:5601" # web ui
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
    depends_on:
      - opensearch
  rabbitmq:
    image: rabbitmq:4.3-alpine
    ports:
      - "127.0.0.1:15672:15672" # web ui
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_VHOST=magento
  mail:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - "127.0.0.1:8025:8025" # web ui
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis-cache:redis-cache:6379,redis-fpc:redis-fpc:6380,redis-session:redis-session:6381
    ports:
      - "127.0.0.1:8081:8081" #web UI
    depends_on:
      - redis-cache
      - redis-fpc
      - redis-session
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
volumes:
  mariadb:
  osdata:
  redis-session:
  redis-cache:
  redis-fpc:
